Module/UW/MI/CouplingPropagation set Nt_ 20
Module/UW/MI/CouplingPropagation set Nr_ 20
Module/UW/MI/CouplingPropagation set at_ 0.10
Module/UW/MI/CouplingPropagation set ar_ 0.10
Module/UW/MI/CouplingPropagation set Rt_ 2.0
Module/UW/MI/CouplingPropagation set Rr_ 2.0
Module/UW/MI/CouplingPropagation set kappa_ 1.0
Module/UW/MI/CouplingPropagation set mu_r_ 1.0
Module/UW/MI/CouplingPropagation set use_cond_loss_ 1
Module/UW/MI/CouplingPropagation set sigma_ 4.0
Module/UW/MI/CouplingPropagation set debug_ 0
